import type { Metadata } from "next";

import "./globals.css";
import { AppProviders } from "./providers";
import { Navigation } from "@/components/composed/navigation/Navigation";
import { Screen } from "@/components/ui/surfaces/Screen";
import { background } from "@/styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={`min-h-full h-screen flex flex-row overflow-hidden ${background.bluepurplegradient}`}>
        <AppProviders>
          <Navigation />
          <Screen>
            {children}

          </Screen>

        </AppProviders>

      </body>
    </html>
  );
}
