import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "./providers";
import { Navigation } from "@/components/navigation/navigation";
import { Screen } from "@/components/layout/screen";
import { background } from "@/styles";
import { Card, Label } from "@heroui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`min-h-full h-screen flex flex-row overflow-hidden ${background.bluepurplegradient}`}>
        <AppProviders>
          <Navigation />
          <Screen>
            {children}

          </Screen>

        </AppProviders>

      </body>
    </html>
  );
}
